name: hydraulics_AI_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - brotli-python
  - bzip2
  - ca-certificates
  - certifi
  - charset-normalizer
  - ffmpeg
  - filelock
  - freetype
  - gmp
  - gmpy2
  - gnutls
  - idna
  - jinja2
  - jpeg
  - lame
  - lcms2
  - lerc
  - libdeflate
  - libffi
  - libiconv
  - libidn2
  - libpng
  - libtasn1
  - libtiff
  - libunistring
  - libuuid
  - libwebp-base
  - lz4-c
  - markupsafe
  - mpc
  - mpfr
  - mpmath
  - ncurses
  - nettle
  - networkx
  - numpy
  - numpy-base
  - openh264
  - openjpeg
  - openssl
  - pillow
  - pip
  - pysocks
  - python=3.10
  - pytorch
  - readline
  - requests
  - setuptools
  - sqlite
  - sympy
  - tbb
  - tk
  - torchaudio
  - torchvision
  - typing_extensions
  - urllib3
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
      - contourpy==1.2.1
      - cycler==0.12.1
      - fonttools==4.51.0
      - imageio==2.34.0
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - matplotlib==3.8.4
      - opencv-python-headless==4.9.0.80
      - packaging==24.0
      - pandas==2.2.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - scikit-image==0.23.1
      - scipy==1.13.0
      - shapely==2.0.4
      - six==1.16.0
      - tifffile==2024.4.18
      - tqdm==4.66.2
      - tzdata==2024.1

